### ISSUE TITLE
problems with git clone 

### ISSUE THREAD

**Issue by HegedusB** [hillerlab/GenomeAlignmentTools#1]
The 'git clone http://genome-source.cse.ucsc.edu/kent.git' is not working for me.

**Comment by MichaelHiller** [comment]
Hi, 

I tried to git clone and also got an error: error: Failed connect to genome-source.cse.ucsc.edu:80; No route to host (curl_result = 7, http_code = 0, sha1 = 3a7ef3b96220c234c8eda26aa532a82474c107d0) 

I guess the UCSC browser group will fix that very soon. 
If not, pls contact them as this is their git repo.

Best, 
- Michael
