### ISSUE TITLE
What are tDb and qDb of netClass input data ?

### ISSUE THREAD

**Issue by Yanglv-rookie** [hillerlab/GenomeAlignmentTools#12]
Hi, respected Sir，
When I executed NetFilterNonNested.perl, I was told that
```
$ NetFilterNonNested.perl ARS-UCD.net -doUCSCSynFilter -keepSynNetsWithScore 5000 -keepInvNetsWithScore 5000
ERROR: parameter -keepSynNetsWithScore/-keepInvNetsWithScore-doUCSCSynFilter is given, but I cannot parse the net type from this fill line: fill 54369 150 NW_017212635.1 + 13997 150 id 4533855 score 3186 ali 150
```
So, I need to execute netClass before NetFilterNonNested, but I don't know what tDB and qDb are and how to get it.So please let me know.   
Thank you in advance for your answers!
```
netClass - Add classification info to net
usage:
   netClass [options] in.net tDb qDb out.net
       tDb - database to fetch target repeat masker table information
       qDb - database to fetch query repeat masker table information
```

**Comment by MichaelHiller** [comment]
netClass is a UCSC tool and tDb / qDb point towards the target and query assemblies. I think, for each assembly, you must have a SQL database. 
Not sure whether UCSC has a database-free version of netClass, but could be worth asking.

**Comment by Yanglv-rookie** [comment]
Dear [MichaelHiller](https://github.com/MichaelHiller),
Thank you very much for your reply, this seems to be a very tricky issue. In your paper of _A genome alignment of 120 mammals highlights ultraconserved element variability and placenta-associated enhancers_, how did you solve this problem, does UCSC provide these SQL databases?

**Comment by MichaelHiller** [comment]
Well, we have a full UCSC browser mirror and the SQL database. :-)
Pls let me know if there is a database-free option and we will included that in the filtering procedure

**Comment by Yanglv-rookie** [comment]
Dear [MichaelHiller](https://github.com/MichaelHiller), Sorry for taking so long to reply to you, I think there may not be no database-free option for netClass, so I got the MYSQL database to solve this problem, now netClass is working.
Thank you for your previous answers!Best wishes to you!

**Comment by Yanglv-rookie** [comment]
Dear [MichaelHiller](https://github.com/MichaelHiller),
I have studied your paper of A genome alignment of 120 mammals highlights ultraconserved element variability and placenta-associated enhancers. But I can't get the sql files of goat and buffalo in UCSC, should I make these sql files? What tools should I use to achieve this?

**Comment by MichaelHiller** [comment]
Which SQL files do you mean? The 2bit files? 
Looks like UCSC moved some assemblies into assembly hubs, e.g. 
http://genome.ucsc.edu/cgi-bin/hgTracks?db=hub_1593943_bubBub1

**Comment by Yanglv-rookie** [comment]
I need the simpleRepeat and rmsk SQL files of buffalo. I can get a SQL file list from `rsync -hna --stats rsync://hgdownload.soe.ucsc.edu/mysql/`, but some species are not included in the list.

**Comment by MichaelHiller** [comment]
I see. Could be that UCSC deleted the SQL database for those 2 species when they moved that into an assembly hub. I would ask UCSC for these files if both species are critical for you (there are many other mammal genomes available)

**Comment by Yanglv-rookie** [comment]
Thanks again for your patient answer, I will consult with UCSC.
Best wishes!
