### ISSUE TITLE
Missing ExtractSynInvChainsFromNet.perl

### ISSUE THREAD

**Issue by andreirozanski** [hillerlab/GenomeAlignmentTools#15]
Dear Michael,

I gave FilterChains_Net_FilterNets.perl a try:

```
sh: line 1: ExtractSynInvChainsFromNet.perl: command not found     
Uncaught exception from user code:    
        ERROR: ExtractSynInvChainsFromNet.perl command failed   
```

Thanks 
AndreiR

**Comment by MichaelHiller** [comment]
I have uploaded the script. I think that is the only script that was missing.

**Comment by andreirozanski** [comment]
Great! Thanks for that.

**Comment by andreirozanski** [comment]
Hi Michael,

I have checked the file and I am getting:

```
-idFile is not a valid option
ERROR: chainPreNet command failed
call: set -o pipefail; chainFilter -idFile= ...
```
From : 
https://github.com/hillerlab/GenomeAlignmentTools/blob/29532812fda2c4380135afef7d9559aa9403dcfc/src/ExtractSynInvChainsFromNet.perl#L99

there's a call using idFile parameter which does not seem to be a valid chainFilter parameter.

Thanks!
Best,
AndreiR

**Comment by MichaelHiller** [comment]
I updated https://github.com/hillerlab/GenomeAlignmentTools/blob/master/kent/src/hg/mouseStuff/chainFilter/chainFilter.c which now has this new parameter that I added to chainFilter. Pls git pull and recompile the kent binaries. Afterwards chainFilter should show this option

**Comment by andreirozanski** [comment]
Great! thanks. I am now facing a similar issue with chainNet:

```
-rescore is not a valid option
```

Thanks!
AndreiR

**Comment by MichaelHiller** [comment]
Good catch. I realized that we had 2 chainNet version in this repo. One in kent/src/hg/mouseStuff (which is the original version) and one in https://github.com/hillerlab/GenomeAlignmentTools/tree/master/src which has the new -rescore option.
I have removed building chainNet from kent/src/hg/mouseStuff/makefile.
As a result, if you rm the chainNet binary and recompile, you should only get the new one from https://github.com/hillerlab/GenomeAlignmentTools/tree/master/src.
Let me know if that works

**Comment by andreirozanski** [comment]
Great. Thanks.
