### ISSUE TITLE
error when running repeatfiller on mm10 chromosome chr12_GL456349_alt

### ISSUE THREAD

**Issue by yr-gh** [hillerlab/GenomeAlignmentTools#18]
Dear all,

Now I'm running RepeatFiller.py on my genomes (target - mm10, query - mink, sequenced by ourselves), but I met the following error when I run it with the chain file of mm10 chromosome chr12_GL456349_alt:

Traceback (most recent call last):
  File "/gpfs/home/yangrui/softs/GenomeAlignmentTools-master/src/RepeatFiller.py", line 396, in <module>
    curMiniBlockLines = GetChainBlockFromLastzOutput(allMiniChainLines, next_pos)
  File "/gpfs/home/yangrui/softs/GenomeAlignmentTools-master/src/RepeatFiller.py", line 224, in GetChainBlockFromLastzOutput
    raise ValueError('ERROR! allMiniChainsSplit start separator line at position ' + str(position) + ' does not start with LINE...')
ValueError: ERROR! allMiniChainsSplit start separator line at position 0 does not start with LINE...

It seems this chain file generated by mm10 chr12_GL456349_alt vs all mink chrs is smaller and simpler than those chains generated by mm10 chr1/2/3/...

Can you tell me whether I can directly delete this problem chain file from the following steps? It seems this chr chr12_GL456349_alt is not so important.

In additition, can you tell me what situations will raise this error?

Thank you!

**Comment by yr-gh** [comment]
by the way, i run RepeatFiller.py on each target chromosome (i.e. in a chromosome-split way).

if i merge all chains into one, then run it with the all.chain, can this error be avoided?

Thank you very much!

**Comment by MichaelHiller** [comment]
Thanks for reporting that issue. We think we have a fix and Ekaterina will upload that soon.

**Comment by osipovarev** [comment]
@yr-gh Thanks a lot for reporting the issue!
It is now fixed. It was likely due to some changes in the output format of last.
Could you please try again and let us know how it goes?

**Comment by yr-gh** [comment]
@osipovarev Thanks for your great help!
Now, there is no error raised when I re-run the RepeatFiller.py on my data.
It seems filtering out chain files (i.e. not generating any output for these files) generated by axtChain which appears almost no any alignment between target and query  automatically (I run RepeatFiller.py in a chromosome-split way).
But I think this manner should have no effect on downstream analyses.
Because these contains almost no reliable alignments between target and query.
Thanks again!

**Comment by yr-gh** [comment]
@osipovarev I'm sorry to bother you again.
As said above, I can run all chain files with RepeatFiller.py smoothly.
But it seems leading to another error when I sort these repeat-filled chain files when using UCSC chainSort, the error just like this:

q end mismatch 210054446 vs 210099079 line 278636 of /gpfs/home/yangrui/mywd/lastz_mink_mm10/repeatfiller/res/chain_filled/chr1.rf.chain

I am not sure whether this error is caused by RepeatFiller.py.
But one this is certain that I can sort these repeat-filled chain files without any error which are ran by the old RepeatFiller.py.

Thanks!

**Comment by osipovarev** [comment]
Could I ask you to share the data so I could reproduce the issue and work on it? Just a file with a chain where you have this issue running repeatFiller followed by chainSort would suffice.
Thanks!

**Comment by yr-gh** [comment]
@osipovarev

Sorry for sending the file to you now!

I've sent one of the chain files where some issues were raised when running them with RepeatFiller.py as well as corresponding 2bit files to your mail osipovarev@gmail.com.

Thank you for your great help!

**Comment by osipovarev** [comment]
Thanks a lot for sending the files, I am running tests with your data now. Could you also provide the exact call of RepeatFiller?

**Comment by yr-gh** [comment]
@osipovarev 

This is my settings of running RepeatFiller.py:

RepeatFiller.py -c ${chain} -T2 ${target_2bit} -Q2 ${query_2bit} -o ${chain_filled} > ${out} 2> ${err}

and here is my settings about lastz_32 and axtChain:

K=2400 L=3000 Y=9400 H=2000 O=400 E=30 T=1 --ambiguous=n --ambiguous=iupac --format=axt --allocate:traceback=1.99G

axtChain ${axtChain_params} ${axt} ${target_2bit} ${query_2bit} ${chain} > ${out} 2> ${err}

where axtChain_params is axtChain_params="-minScore=3000 -linearGap=medium"

For the chain file I've sent to you, it can be ran without exceptions by using the old RepeatFiller.py, but cannot be ran with the latest one you fixed just soon.

Thank you for great help!

**Comment by yr-gh** [comment]
@osipovarev 

It seems no error occurred when I ran the resulting chain file you sent to me with chainSort.

Previously, there was an error occurred when I ran the resulting chain file generated by the latest RepeatFiller.py with chainSort.

Sorry for taking you too much time!

Thanks for your great help!
