### ISSUE TITLE
Versioned package release request

### ISSUE THREAD

**Issue by jayramr** [hillerlab/GenomeAlignmentTools#19]
I'm working to make Repeatfiller/chainfiller available on Bioconda.

Please refer. -> https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

I need your help creating a versioned release to use for the Bioconda recipe. Once this is added to Bioconda, it'll also be made available as a Docker container from Biocontainers, and as a Singularity image from the Galaxy Project. The Bioconda bot will also recognize future releases and automatically update the recipe.

Please let me know

Thanks
Jay

**Comment by MichaelHiller** [comment]
Done. Thanks Jay
