### ISSUE TITLE
Error when compiling chainNet and other binaries

### ISSUE THREAD

**Issue by GiuliaPasquesi** [hillerlab/GenomeAlignmentTools#2]
I followed the installation instructions, but when I get at the compiling part for chainCleaner, chainNet and scoreChain, I get the following error:

gcc -I/inc -I/hg/inc -O4 -static -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized   -c -o chainNet.o chainNet.c
chainNet.c:10:20: fatal error: common.h: No such file or directory
 #include "common.h"
                    ^
compilation terminated.
make: *** [chainNet.o] Error 1

Am I missing some steps?

**Comment by MichaelHiller** [comment]
Hi,

Please check the value of the bash variable 
echo $KENTSRC_DIR
It should point to the path of the kent source installation, which contains common.h in src/inc/

This variable is used in GenomeAlignmentTools/src/chainNet/makefile and the other makefiles. 

INCS = -I$(KENTSRC_DIR)/inc -I$(KENTSRC_DIR)/hg/inc

Best
Michael
