### ISSUE TITLE
Update axtChain

### ISSUE THREAD

**Issue by plattsad** [hillerlab/GenomeAlignmentTools#25]
Hey all,

You may want to consider updating axtChain depending on how you call it.  There's also maybe a few more bugs been addressed since the below I think (just based on compiled file sizes):

https://github.com/ucscGenomeBrowser/kent/commit/7106942562801f0a7a7c9dc4c101c9f7e8afc1a8?diff=split

**Comment by MichaelHiller** [comment]
Thx for letting me know. 
Fortunately, this axtChain bug was only relevant for those that read fasta files and we have always been using 2bit. 
I'll update it when we pull the newest UCSC src.

**Comment by MichaelHiller** [comment]
The updated axtChain.c is git committed now. Thx for the heads up.
