### ISSUE TITLE
chainCleaner failed

### ISSUE THREAD

**Issue by yuzhenpeng** [hillerlab/GenomeAlignmentTools#3]
Hi, Teamers.
Recent days, I met a lot problems when used the chainCleaner. Could you please give me some help.
my command was list as follow:
`chainCleaner out.chain.gz -tSizes=../target.sizes -qSizes=../query.sizes ../target.2bit ../query.2bit out.clean.chain removedSuspects.bed -linearGap=medium`
But I got some warnings:
![image](https://user-images.githubusercontent.com/31943277/81463661-b5b47280-91ed-11ea-974d-bbc1d5e94f49.png)

Thank you. @MichaelHiller

**Comment by MichaelHiller** [comment]
Hi Zhenpeng, 
a segfault is a real crash. 
To debug this, I would need all input files. Can you send me a download link to my email address? 

thanks
Michael

**Comment by yuzhenpeng** [comment]
Hi Michael,
Thank for your positive response. Now I fixed it with new version of chainCleaner. It seems very well.

Thank you.
Zhengpeng.
