### ISSUE TITLE
issue compiling 

### ISSUE THREAD

**Issue by lecook** [hillerlab/GenomeAlignmentTools#6]
Hello,

I am trying to install the tools using the following commands:

git clone https://github.com/hillerlab/GenomeAlignmentTools.git
cd GenomeAlignmentTools/kent/src
make

I get the following error:

hmac.c:11:26: fatal error: openssl/hmac.h: No such file or directory
 #include "openssl/hmac.h"
                          ^
compilation terminated.
make[1]: *** [hmac.o] Error 1
make[1]: Leaving directory `/data/gpfs/projects/punim0586/lecook/chipseq-pipeline/cross_species/data/genomes/chain/GenomeAlignmentTools/kent/src/lib'
make: *** [topLibs] Error 2

Any assistance with this error would be greatly appreciated!
Thank you.

Laura Cook

**Comment by MichaelHiller** [comment]
Hi Laura, 
I googled the error and found this
https://github.com/derniercri/snatch/issues/34

Did you install libssl-dev ? 

Michael

**Comment by lecook** [comment]
Hi Michael,

Thanks for your help. Yes I had to install libssl-dev, libpng and libuuid and then it worked!

Cheers,
Laura
